name: mivoto_flutter
description: Aplicación Flutter para MiVoto (cliente móvil)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3
  url_launcher: ^6.2.5
  avatar_glow: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


